//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ModelID { get; set; }
        public int LineID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
